
export const SERVICES = [
    { name: "Internet of Things (IOT)", slug: "internet-of-things-iot" },
    { name: "Staff Augmentation Services", slug: "staff-augmentation-services" },
    { name: "Cloud Consulting", slug: "cloud-consulting" },
    { name: "Big Data Analytics", slug: "big-data-analytics" },
    { name: "Managed Service Providers", slug: "managed-service-providers" },
    { name: "IT Services", slug: "it-services" },
    { name: "Software Testing", slug: "software-testing" },
    { name: "Blockchain Development", slug: "blockchain-development" },
    { name: "iPhone App Development", slug: "iphone-app-development" },
    { name: "Android App Development", slug: "android-app-development" },
    { name: "AI Development", slug: "ai-development" },
    { name: "VR & Augmented Reality", slug: "vr-augmented-reality" },
    { name: "Software Development", slug: "software-development" },
    { name: "WordPress Development", slug: "wordpress-development" },
    { name: "Shopify Development", slug: "shopify-development" },
    { name: "Web Design", slug: "web-design" },
    { name: "Web Development", slug: "web-development" },
    { name: "UI/UX Design Services", slug: "ui-ux-design-services" },
    { name: "Cybersecurity Services", slug: "cybersecurity-services" }
]

export const CITIES = [
    { name: "New York", slug: "new-york", state: "NY" },
    { name: "Los Angeles", slug: "los-angeles", state: "CA" },
    { name: "Chicago", slug: "chicago", state: "IL" },
    { name: "Houston", slug: "houston", state: "TX" },
    { name: "Phoenix", slug: "phoenix", state: "AZ" },
    { name: "Philadelphia", slug: "philadelphia", state: "PA" },
    { name: "San Antonio", slug: "san-antonio", state: "TX" },
    { name: "San Diego", slug: "san-diego", state: "CA" },
    { name: "Dallas", slug: "dallas", state: "TX" },
    { name: "San Jose", slug: "san-jose", state: "CA" },
    { name: "Austin", slug: "austin", state: "TX" },
    { name: "Jacksonville", slug: "jacksonville", state: "FL" },
    { name: "Fort Worth", slug: "fort-worth", state: "TX" },
    { name: "Columbus", slug: "columbus", state: "OH" },
    { name: "San Francisco", slug: "san-francisco", state: "CA" },
    { name: "Charlotte", slug: "charlotte", state: "NC" },
    { name: "Indianapolis", slug: "indianapolis", state: "IN" },
    { name: "Seattle", slug: "seattle", state: "WA" },
    { name: "Denver", slug: "denver", state: "CO" },
    { name: "Washington", slug: "washington", state: "DC" },
    { name: "Boston", slug: "boston", state: "MA" },
    { name: "El Paso", slug: "el-paso", state: "TX" },
    { name: "Nashville", slug: "nashville", state: "TN" },
    { name: "Detroit", slug: "detroit", state: "MI" },
    { name: "Oklahoma City", slug: "oklahoma-city", state: "OK" },
    { name: "Portland", slug: "portland", state: "OR" },
    { name: "Las Vegas", slug: "las-vegas", state: "NV" },
    { name: "Memphis", slug: "memphis", state: "TN" },
    { name: "Louisville", slug: "louisville", state: "KY" },
    { name: "Baltimore", slug: "baltimore", state: "MD" },
    { name: "Milwaukee", slug: "milwaukee", state: "WI" },
    { name: "Albuquerque", slug: "albuquerque", state: "NM" },
    { name: "Tucson", slug: "tucson", state: "AZ" },
    { name: "Fresno", slug: "fresno", state: "CA" },
    { name: "Mesa", slug: "mesa", state: "AZ" },
    { name: "Sacramento", slug: "sacramento", state: "CA" },
    { name: "Atlanta", slug: "atlanta", state: "GA" },
    { name: "Kansas City", slug: "kansas-city", state: "MO" },
    { name: "Colorado Springs", slug: "colorado-springs", state: "CO" },
    { name: "Miami", slug: "miami", state: "FL" },
    { name: "Raleigh", slug: "raleigh", state: "NC" },
    { name: "Omaha", slug: "omaha", state: "NE" },
    { name: "Long Beach", slug: "long-beach", state: "CA" },
    { name: "Virginia Beach", slug: "virginia-beach", state: "VA" },
    { name: "Oakland", slug: "oakland", state: "CA" },
    { name: "Minneapolis", slug: "minneapolis", state: "MN" },
    { name: "Tulsa", slug: "tulsa", state: "OK" },
    { name: "Tampa", slug: "tampa", state: "FL" },
    { name: "Arlington", slug: "arlington", state: "TX" },
    { name: "New Orleans", slug: "new-orleans", state: "LA" }
]

// Fallback data - used if DB has no entries or connection fails
export const FALLBACK_AGENCIES = [
    {
        rank: 1,
        name: "tkxel",
        slug: "tkxel",
        tagline: "Top-Rated Digital Transformation Partner",
        clutchRating: 5.0,
        websiteUrl: "https://tkxel.com",
        services: ["Software Development", "UI/UX Design", "Mobile Apps", "AI Solutions"],
        description: "tkxel is a leading technology partner for Fortune 500s and ambitious startups. With 15+ years of excellence, they craft award-winning digital experiences that drive real business growth. Their design philosophy blends aesthetic brilliance with data-driven usability.",
        whyChoose: "tkxel stands out for its **holistic approach**—combining world-class design with robust engineering. They don't just design interfaces; they build **scalable digital ecosystems**. With 700+ experts and 24/7 support, they act as a true extension of your team.",
        minProjectSize: "$25,000+",
        hourlyRate: "$25 - $49 / hr",
        employeesCount: "700+",
        yearFounded: "2008",
        reviewsCount: 85,
        clutchUrl: "tkxel",
        location: "Reston, VA",
    },
    {
        rank: 2,
        name: "Elevate Digital",
        slug: "elevate-digital",
        tagline: "Premium Enterprise Software Solutions",
        clutchRating: 4.9,
        websiteUrl: "https://elevatedigital.sg",
        services: ["Enterprise Software", "Cloud Consulting", "UI/UX Design"],
        description: "Elevate Digital specializes in building high-performance software for large-scale enterprises. They focus on security, scalability, and seamless integration with existing systems.",
        whyChoose: "Known for their **enterprise-grade security** and compliance expertise. Perfect for fintech and healthcare projects requiring strict adherence to regulations.",
        minProjectSize: "$50,000+",
        hourlyRate: "$50 - $99 / hr",
        employeesCount: "250+",
        yearFounded: "2012",
        reviewsCount: 42,
        clutchUrl: null,
        location: "San Francisco, CA",
    },
    {
        rank: 3,
        name: "Orbit Soft",
        slug: "orbit-soft",
        tagline: "Agile Development for Modern Startups",
        clutchRating: 4.8,
        websiteUrl: "https://orbitsoft.com",
        services: ["Mobile App Development", "Web Development", "MVP Construction"],
        description: "Orbit Soft is the go-to partner for startups looking to launch fast. Their agile methodology ensures rapid iteration and quick time-to-market without compromising quality.",
        whyChoose: "They offer **rapid MVP development** packages and a flexible engagement model. Great for founders who need to validate ideas quickly.",
        minProjectSize: "$10,000+",
        hourlyRate: "$40 / hr",
        employeesCount: "50+",
        yearFounded: "2018",
        reviewsCount: 65,
        clutchUrl: null,
        location: "Austin, TX",
    },
    {
        rank: 4,
        name: "Nexus Innovations",
        slug: "nexus-innovations",
        tagline: "AI-Powered Business Solutions",
        clutchRating: 4.7,
        websiteUrl: "https://nexus-innovations.com",
        services: ["AI Development", "Machine Learning", "Data Analytics"],
        description: "Nexus Innovations brings the power of Artificial Intelligence to your business. From predictive analytics to custom LLM integration, they help companies leverage data for growth.",
        whyChoose: "Deep expertise in **Generative AI** and data strategy. They act as strategic consultants, not just coders.",
        minProjectSize: "$35,000+",
        hourlyRate: "$100 - $149 / hr",
        employeesCount: "120+",
        yearFounded: "2015",
        reviewsCount: 28,
        clutchUrl: null,
        location: "New York, NY",
    },
    {
        rank: 5,
        name: "Spark Creative",
        slug: "spark-creative",
        tagline: "Award-Winning UI/UX Design Studio",
        clutchRating: 4.9,
        websiteUrl: "https://sparkcreative.com",
        services: ["UI/UX Design", "Branding", "Web Design"],
        description: "Spark Creative is a boutique design studio obsessed with pixel perfection. They create visually stunning interfaces that tell a compelling brand story.",
        whyChoose: "Their **design-first approach** ensures your product looks world-class. Winners of multiple Awwwards and design accolades.",
        minProjectSize: "$5,000+",
        hourlyRate: "$60 - $80 / hr",
        employeesCount: "25+",
        yearFounded: "2020",
        reviewsCount: 110,
        clutchUrl: null,
        location: "Los Angeles, CA",
    },
    {
        rank: 6,
        name: "CodeCraft Labs",
        slug: "codecraft-labs",
        tagline: "Reliable Backend & API Development",
        clutchRating: 4.6,
        websiteUrl: "https://codecraft.com",
        services: ["Backend Development", "API Integration", "DevOps"],
        description: "CodeCraft Labs handles the heavy lifting behind the scenes. They build robust backends, scalable APIs, and reliable cloud infrastructure.",
        whyChoose: "Focus on **performance and uptime**. If you need a system that never crashes, these are the engineers to call.",
        minProjectSize: "$15,000+",
        hourlyRate: "$30 / hr",
        employeesCount: "80+",
        yearFounded: "2016",
        reviewsCount: 55,
        clutchUrl: null,
        location: "Denver, CO",
    }
]
