export const SERVICES = [
    { name: "Internet of Things (IOT)", slug: "internet-of-things-iot" },
    { name: "Staff Augmentation Services", slug: "staff-augmentation-services" },
    { name: "Cloud Consulting", slug: "cloud-consulting" },
    { name: "Big Data Analytics", slug: "big-data-analytics" },
    { name: "Managed Service Providers", slug: "managed-service-providers" },
    { name: "IT Services", slug: "it-services" },
    { name: "Software Testing", slug: "software-testing" },
    { name: "Blockchain Development", slug: "blockchain-development" },
    { name: "iPhone App Development", slug: "iphone-app-development" },
    { name: "Android App Development", slug: "android-app-development" },
    { name: "AI Development", slug: "ai-development" },
    { name: "VR & Augmented Reality", slug: "vr-augmented-reality" },
    { name: "Software Development", slug: "software-development" },
    { name: "WordPress Development", slug: "wordpress-development" },
    { name: "Shopify Development", slug: "shopify-development" },
    { name: "Web Design", slug: "web-design" },
    { name: "Web Development", slug: "web-development" },
    { name: "UI/UX Design Services", slug: "ui-ux-design-services" },
    { name: "Cybersecurity Services", slug: "cybersecurity-services" }
]

export const CITIES = [
    { name: "New York", slug: "new-york", state: "NY" },
    { name: "Los Angeles", slug: "los-angeles", state: "CA" },
    { name: "Chicago", slug: "chicago", state: "IL" },
    { name: "Houston", slug: "houston", state: "TX" },
    { name: "Phoenix", slug: "phoenix", state: "AZ" },
    { name: "Philadelphia", slug: "philadelphia", state: "PA" },
    { name: "San Antonio", slug: "san-antonio", state: "TX" },
    { name: "San Diego", slug: "san-diego", state: "CA" },
    { name: "Dallas", slug: "dallas", state: "TX" },
    { name: "San Jose", slug: "san-jose", state: "CA" },
    { name: "Austin", slug: "austin", state: "TX" },
    { name: "Jacksonville", slug: "jacksonville", state: "FL" },
    { name: "Fort Worth", slug: "fort-worth", state: "TX" },
    { name: "Columbus", slug: "columbus", state: "OH" },
    { name: "San Francisco", slug: "san-francisco", state: "CA" },
    { name: "Charlotte", slug: "charlotte", state: "NC" },
    { name: "Indianapolis", slug: "indianapolis", state: "IN" },
    { name: "Seattle", slug: "seattle", state: "WA" },
    { name: "Denver", slug: "denver", state: "CO" },
    { name: "Washington", slug: "washington", state: "DC" },
    { name: "Boston", slug: "boston", state: "MA" },
    { name: "El Paso", slug: "el-paso", state: "TX" },
    { name: "Nashville", slug: "nashville", state: "TN" },
    { name: "Detroit", slug: "detroit", state: "MI" },
    { name: "Oklahoma City", slug: "oklahoma-city", state: "OK" },
    { name: "Portland", slug: "portland", state: "OR" },
    { name: "Las Vegas", slug: "las-vegas", state: "NV" },
    { name: "Memphis", slug: "memphis", state: "TN" },
    { name: "Louisville", slug: "louisville", state: "KY" },
    { name: "Baltimore", slug: "baltimore", state: "MD" },
    { name: "Milwaukee", slug: "milwaukee", state: "WI" },
    { name: "Albuquerque", slug: "albuquerque", state: "NM" },
    { name: "Tucson", slug: "tucson", state: "AZ" },
    { name: "Fresno", slug: "fresno", state: "CA" },
    { name: "Mesa", slug: "mesa", state: "AZ" },
    { name: "Sacramento", slug: "sacramento", state: "CA" },
    { name: "Atlanta", slug: "atlanta", state: "GA" },
    { name: "Kansas City", slug: "kansas-city", state: "MO" },
    { name: "Colorado Springs", slug: "colorado-springs", state: "CO" },
    { name: "Miami", slug: "miami", state: "FL" },
    { name: "Raleigh", slug: "raleigh", state: "NC" },
    { name: "Omaha", slug: "omaha", state: "NE" },
    { name: "Long Beach", slug: "long-beach", state: "CA" },
    { name: "Virginia Beach", slug: "virginia-beach", state: "VA" },
    { name: "Oakland", slug: "oakland", state: "CA" },
    { name: "Minneapolis", slug: "minneapolis", state: "MN" },
    { name: "Tulsa", slug: "tulsa", state: "OK" },
    { name: "Tampa", slug: "tampa", state: "FL" },
    { name: "Arlington", slug: "arlington", state: "TX" },
    { name: "New Orleans", slug: "new-orleans", state: "LA" }
]
